In [3]:
import scipy as sp
import numpy as np 

In [11]:
N = 20 
N_types = 3
A = np.zeros((N, N_types))

In [54]:
# value of time = 1
A[:, -1] = -1
# value of money 
A[:, 1] = - np.random.randint(1, 11, N)
# value of good
A[:, 0] = np.random.randint(1, 11, N)

In [162]:
A = np.array([[100, -100, -1], [1, -1, -1]])

In [163]:
A

array([[ 100, -100,   -1],
       [   1,   -1,   -1]])

In [197]:
def obj(menu, agents, alpha = 1, q = 1): 
    # N_type is (x, p, t)
    # menu is N_type * number of menu items
    menu = menu.reshape((-1, 3))
    menu_zero = np.vstack((menu, [0, 0, 0]))    
    # get utility of each menu item for each agent
    val = agents.dot(menu_zero.T)
    # get menu item chosen
    menu_util_chosen = np.argmax(val, 1)
    # get menu item chosen utility
    menu_util = np.max(val, 1)
    # calculate welfare
    welfare = np.sum(menu_util)
    # calculate revenue
    revenue = np.sum(menu_zero[menu_util_chosen, 1])
    quantity = np.sum(menu_zero[menu_util_chosen, 0])
    V = welfare + alpha * revenue if quantity <= q else 0
    return - V

In [191]:
menu.shape

(3,)

In [193]:
def constraints_fn(x):
    allocations = x[0]
    prices = x[1]
    times = x[2]
    
    constraints = []
    
    constraints.append(allocations) # >= 0 
    constraints.append(1 - allocations) # <= 1
    
    constraints.append(prices) # >= 0 
    constraints.append(times)  # >= 0 
    
    con = np.array(constraints)
    
    return con

In [94]:
obj(menu, np.vstack((A, [10000, -1, -1])))

[[-3.3800e+00 -6.8100e+00  0.0000e+00]
 [-3.2800e+00 -6.3600e+00  0.0000e+00]
 [-1.8000e-01 -8.1000e-01  0.0000e+00]
 [-3.5800e+00 -6.6600e+00  0.0000e+00]
 [-1.1800e+00 -2.5100e+00  0.0000e+00]
 [-2.9800e+00 -6.0600e+00  0.0000e+00]
 [-2.0800e+00 -4.1100e+00  0.0000e+00]
 [-1.0800e+00 -1.7100e+00  0.0000e+00]
 [-2.5800e+00 -5.3100e+00  0.0000e+00]
 [-2.5800e+00 -4.9600e+00  0.0000e+00]
 [-1.3800e+00 -2.7100e+00  0.0000e+00]
 [-2.7800e+00 -5.5100e+00  0.0000e+00]
 [-2.9800e+00 -5.7100e+00  0.0000e+00]
 [-3.8800e+00 -7.3100e+00  0.0000e+00]
 [-2.5800e+00 -4.6100e+00  0.0000e+00]
 [-2.5800e+00 -4.9600e+00  0.0000e+00]
 [-2.8800e+00 -5.6100e+00  0.0000e+00]
 [-3.0800e+00 -6.1600e+00  0.0000e+00]
 [-1.3800e+00 -2.7100e+00  0.0000e+00]
 [-2.2800e+00 -3.9600e+00  0.0000e+00]
 [ 9.9922e+02  9.9894e+02  0.0000e+00]]
welf 999.22
rev 0.4


999.62

In [217]:
menu = np.array([0.7, 0.2, 50])

In [218]:
constraints = {'type': 'ineq', 'fun' : constraints_fn}

In [219]:
res = sp.optimize.minimize(
    obj, 
    menu, 
    method = 'COBYLA', 
    constraints = constraints, 
    args = (A), 
    options = {"maxiter": 100000}
)

In [220]:
res

     fun: -98.99008032431666
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 47246
  status: 1
 success: True
       x: array([1.00000000e+00, 1.00000000e-04, 1.00001968e+00])

In [221]:
np.round(res.x, 3)

array([1., 0., 1.])